In [1]:
import numpy as np
import numpy.linalg as LA

In [5]:
A = np.array([[2, -1], [0, 3]])
B= np.array([[1, 2], [-3, 4]])
# A + B
add_result = A + B
# AB
mul_result = A @ B
# 3A - 2B
exp_result = 3*A - 2*B
print("A + B:\n", add_result)
print("AB:\n", mul_result)
print("3A - 2B:\n", exp_result)

A + B:
 [[ 3  1]
 [-3  7]]
AB:
 [[ 5  0]
 [-9 12]]
3A - 2B:
 [[ 4 -7]
 [ 6  1]]


In this code we utilized the @ to do matrix multiplication and + to do addition and * for scalar multiplication

In [9]:
detA = LA.det(A)
print("Determinant of A:", detA)

if detA != 0:
    invA = LA.inv(A)
    print("Matrix A is invertible and")
    print("Inverse of A:\n", invA)
else:
    print("Matrix A is not invertible")

Determinant of A: 6.0
Matrix A is invertible and
Inverse of A:
 [[0.5        0.16666667]
 [0.         0.33333333]]


First we utilized a function of numpy called det to find determinant of the matrix and we checked if the determinant is non zero, we utilized the function of inv form numpy to get inverse of matrix

In [13]:
C = np.array([[4, 1],
              [-2, 1]])
print("Matrix A:\n", A)
eigenvalues, eigenvectors = LA.eig(A)
print("Eigenvalue:")
print(eigenvalues[0], eigenvalues[1])
print("Corresponding Eigenvector:")
print(eigenvectors)

Matrix A:
 [[ 2 -1]
 [ 0  3]]
Eigenvalue:
2.0 3.0
Corresponding Eigenvector:
[[ 1.         -0.70710678]
 [ 0.          0.70710678]]


Here we utilized the numpy function of eig in order to get eigen values and vectors

In [16]:
x = np.array([[4, 1.5, 100],
                [6, 2.0, 150]])
y = np.array([20, 30])
xtranspose = x.T
beta = LA.pinv(xtranspose @ x) @ xtranspose @ y
print("Coefficient vector(beta):\n", beta)
xnew = np.array([8, 3.0, 200])
predictedprice = xnew @ beta
print("Predicted price of car 3:", predictedprice)

Coefficient vector(beta):
 [ 7.98722045e-03 -4.12114787e-13  1.99680511e-01]
Predicted price of car 3: 39.99999999999998


Here we utilized the aspect of vector and its position to predict the price of the third car where we utilized pinv to find the pseudoinverse as normal inverse is not applicable for all tyoe of matrix.